name: Test and Release Container

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build 
        run: cd $GITHUB_WORKSPACE && docker build -t pandare/igloo:penguin .

      - name: Push to dockerhub
        if: github.ref == 'refs/heads/main'
        run: |
          docker login -u pandare -p ${{secrets.pandare_dockerhub}}
          docker push pandare/igloo:penguin
